/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.fbagamehjdt;

import android.widget.TextView;
import android.graphics.Paint;
import android.graphics.LinearGradient;
import android.graphics.Matrix;
import android.content.Context;
import android.util.AttributeSet;
import android.graphics.Canvas;
import android.text.TextPaint;

public class TitleTextView extends TextView {
    private Paint b;
    private LinearGradient c;
    private Matrix d;
    private int e;
    priva = 0x0;
    
    public TitleTextView(Context p1) {
        super(p1);
    }
    
    public TitleTextView(Context p1, AttributeSet p2) {
        super(p1, p2);
    }
    
    protected void onSizeChanged(int p1, int p2, int p3, int p4) {
        // :( Parsing error. Please contact me.
    }
    
    protected void onDraw(Canvas p1) {
        super.onDraw(p1);
        if(d != null) {
            e = (e + (a / 0x5));
            if(e > (a * 0x2)) {
                e = -a;
            }
            d.setTranslate((float)e, 0.0f);
            c.setLocalMatrix(d);
            postInvalidateDelayed(0x64);
        }
    }
}
