/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.fbagamehjdt.MetalSlug3;


public final class BuildConfig {
    public static final boolean a = false;
    public static final String b = "com.fbagamehjdt.MetalSlug3";
    public static final String c = "release";
    public static final String d = "";
    public static final int e = 0x719be2ba;
    public static final String f = "1.4";
}
