/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.arcade.activity.simulator;


public class EmulatorKey {
    public static final int DRAW = 0x2;
    public static final int EMUHASBEGUN = 0x1c;
    public static final int EMUKEYS = 0x18;
    public static final int ERRORKEY = 0xb;
    public static final int MATCHRKEY = 0x2;
    public static final int MATCHSHOWADSTATE = 0x17;
    public static final int P1ENDGAME = 0x3;
    public static final int P1STARTGAME = 0x2;
    public static final int P1WIN = 0x0;
    public static final int P2ENDGAME = 0x30000;
    public static final int P2PCERRORKEY = 0xc;
    public static final int P2PCMODE = 0xf;
    public static final int P2STARTGAME = 0x20000;
    public static final int P2WIN = 0x1;
    public static final int PEERIDKEY = 0x1;
    public static final int PGAMESTATE = 0x1b;
    public static final int PINGKEY = 0xd;
    public static final int PLAYERWATCHEND = 0x16;
    public static final int PSPCMODE = 0x10;
    public static final int REPLAYEND = 0x11;
    public static final int REPLAYKEY = 0xe;
    public static final int SHOWWPSTATE = 0x15;
    public static final int SHOWWSCORE = 0x12;
    public static final int STARTRECORD = 0x4;
    public static final int SYNCSTATEKEY = 0x3;
    public static final int UPLOADRECORD = 0x5;
    public static final int UPLOADRECORD_FAIL = 0x9;
    public static final int UPLOADRECORD_OK = 0x8;
    public static final int UPLOADRECORD_START = 0x7;
    public static final int UPLOADRECORD_STATE = 0x6;
}
