/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.arcade.activity.simulator;

import java.io.File;
import java.io.FileOutputStream;
import java.util.zip.ZipOutputStream;

public class ZipUtil {
    
    public static String a(String p1, String p2) throws Exception {
        // :( Parsing error. Please contact me.
    }
    
    public static void b(String p1, String p2) throws Exception {
        // :( Parsing error. Please contact me.
    }
    
    public static void c(String p1, String p2) throws Exception {
        File localString1 = new File(p1);
        a(localString1.getParent() + File.separator, localString1.getName(), (new FileOutputStream(p2)));
        (new FileOutputStream(p2)).finish();
        (new FileOutputStream(p2)).close();
    }
    
    private static void a(String p1, String p2, ZipOutputStream p3) throws Exception {
        // :( Parsing error. Please contact me.
    }
}
