/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.fbagamehjdt.api;

import android.content.Context;
import android.content.res.Resources;

public class API {
    private static String b = "http://www.xugameplay.com/api/xiaou/";
    public sta = b + "game_startup_ad.php";
    
    public static int a(String p1, Context p2, String p3) {
        // :( Parsing error. Please contact me.
    }
    
    public static int b(String p1, Context p2, String p3) {
        // :( Parsing error. Please contact me.
    }
}
