/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.fbagamehjdt.api;

import android.content.Context;
import android.content.res.Resources;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.StateListDrawable;

public class ResUtil {
    public sta = 0x0;
    
    public static int a(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int b(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int c(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int d(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int e(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int f(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int g(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int h(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int i(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int j(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static int k(Context p1, String p2) {
        // :( Parsing error. Please contact me.
    }
    
    public static StateListDrawable a(Drawable p1, Drawable p2) {
        StateListDrawable localStateListDrawable1 = new StateListDrawable();
        int localconst2 = 0x101009c;
        localStateListDrawable1.addState(new int[] {-localconst2}, p1);
        localStateListDrawable1.addState(new int[] {localconst2}, p2);
        return localStateListDrawable1;
    }
}
