/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;

public interface abstract class Cache {
    
    public abstract void clear();
    
    
    public abstract void clearKeyUri(String p1);
    
    
    public abstract Bitmap get(String p1);
    
    
    public abstract int maxSize();
    
    
    public abstract void set(String p1, Bitmap p2);
    
    
    public abstract int size();
    
    public static final Cache NONE = new Cache() {
        
        public Bitmap get(String p1) {
            return null;
        }
        
        public void set(String p1, Bitmap p2) {
        }
        
        public int size() {
            return 0x0;
        }
        
        public int maxSize() {
            return 0x0;
        }
        
        public void clear() {
        }
        
        public void clearKeyUri(String p1) {
        }
    };
}
