/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;


public interface abstract class Callback {
    
    public abstract void onError();
    
    
    public abstract void onSuccess();
    
}
