/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import java.io.IOException;
import java.io.InputStream;

import android.content.ContentResolver;
import android.content.Context;
import android.content.UriMatcher;
import android.net.Uri;
import android.provider.ContactsContract;

class ContactsPhotoRequestHandler extends RequestHandler {
    private static final int ID_CONTACT = 0x3;
    private static final int ID_DISPLAY_PHOTO = 0x4;
    private static final int ID_LOOKUP = 0x1;
    private static final int ID_THUMBNAIL = 0x2;
    private final Context context;
    private static final UriMatcher matcher;
    
    static {
        matcher = new UriMatcher(-0x1);
        matcher.addURI("com.android.contacts", "contacts/lookup/*/#", 0x1);
        matcher.addURI("com.android.contacts", "contacts/lookup/*", 0x1);
        matcher.addURI("com.android.contacts", "contacts/#/photo", 0x2);
        matcher.addURI("com.android.contacts", "contacts/#", 0x3);
        matcher.addURI("com.android.contacts", "display_photo/#", 0x4);
    }
    
    ContactsPhotoRequestHandler(Context p1) {
        context = p1;
    }
    
    public boolean canHandleRequest(Request p1) {
        // :( Parsing error. Please contact me.
    }
    
    public RequestHandler.Result load(Request p1, int p2) throws IOException {
        // :( Parsing error. Please contact me.
    }
    
    private InputStream getInputStream(Request p1) throws IOException {
        // :( Parsing error. Please contact me.
    }
    
    class ContactPhotoStreamIcs {
        
        static InputStream get(ContentResolver p1, Uri p2) {
            return ContactsContract.Contacts.openContactPhotoInputStream(p1, p2, true);
        }
    }
}
