/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

import android.content.Context;

class ContentStreamRequestHandler extends RequestHandler {
    final Context context;
    
    ContentStreamRequestHandler(Context p1) {
        context = p1;
    }
    
    public boolean canHandleRequest(Request p1) {
        return "content".equals(p1.uri.getScheme());
    }
    
    public RequestHandler.Result load(Request p1, int p2) throws IOException {
        return new RequestHandler.Result(getInputStream(p1), Picasso.LoadedFrom.DISK);
    }
    
    InputStream getInputStream(Request p1) throws FileNotFoundException {
        context = context.getContentResolver();
        return context.openInputStream(p1.uri);
    }
}
