/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import java.lang.ref.WeakReference;

import android.view.ViewTreeObserver;
import android.widget.ImageView;

class DeferredRequestCreator implements ViewTreeObserver.OnPreDrawListener {
    Callback callback;
    final RequestCreator creator;
    final WeakReference<ImageView> target;
    
    DeferredRequestCreator(RequestCreator p1, ImageView p2) {
        this(p1, p2, 0x0);
    }
    
    DeferredRequestCreator(RequestCreator p1, ImageView p2, Callback p3) {
        creator = p1;
        target = new WeakReference(p2);
        callback = p3;
        p2.getViewTreeObserver().addOnPreDrawListener(this);
    }
    
    public boolean onPreDraw() {
        // :( Parsing error. Please contact me.
    }
    
    void cancel() {
        callback = 0x0;
        target = (ImageView)target.get();
        if(target == null) {
            return;
        }
        target = target.getViewTreeObserver();
        if(target.isAlive()) {
            target.removeOnPreDrawListener(this);
        }
    }
}
