/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;
import java.io.InputStream;
import java.io.IOException;
import android.net.Uri;

public interface abstract class Downloader {
    
    public abstract void shutdown();
    
}
