/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import java.io.IOException;

import android.content.Context;
import android.net.Uri;

class FileRequestHandler extends ContentStreamRequestHandler {
    
    FileRequestHandler(Context p1) {
        super(p1);
    }
    
    public boolean canHandleRequest(Request p1) {
        return "file".equals(p1.uri.getScheme());
    }
    
    public RequestHandler.Result load(Request p1, int p2) throws IOException {
        return new RequestHandler.Result(0x0, getInputStream(p1), Picasso.LoadedFrom.DISK, getFileExifRotation(p1.uri));
    }
    
    static int getFileExifRotation(Uri p1) throws IOException {
        // :( Parsing error. Please contact me.
    }
}
