/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;

class GetAction extends Action {
    
    GetAction(Picasso p1, Request p2, int p3, int p4, Object p5, String p6) {
        super(p1, 0x0, p2, p3, p4, 0x0, 0x0, p6, p5, false);
    }
    
    void complete(Bitmap p1, Picasso.LoadedFrom p2) {
    }
    
    public void error() {
    }
}
