/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;
import android.graphics.drawable.Drawable;
import android.widget.ImageView;

class ImageViewAction extends Action {
    Callback callback;
    
    ImageViewAction(Picasso p1, ImageView p2, Request p3, int p4, int p5, int p6, Drawable p7, String p8, Object p9, Callback p10, boolean p11) {
        super(p1, p2, p3, p4, p5, p6, p7, p8, p9, p11);
        callback = p10;
    }
    
    public void complete(Bitmap p1, Picasso.LoadedFrom p2) {
        // :( Parsing error. Please contact me.
    }
    
    public void error() {
        target = (ImageView)target.get();
        if(target == null) {
            return;
        }
        if(errorResId != 0) {
            target.setImageResource(errorResId);
        } else if(errorDrawable != null) {
            target.setImageDrawable(errorDrawable);
        }
        if(callback != null) {
            callback.onError();
        }
    }
    
    void cancel() {
        super.cancel();
        if(callback != null) {
            callback = 0x0;
        }
    }
}
