/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;


public final enum class MemoryPolicy extends Enum {
    final int index;
    
    public static MemoryPolicy valueOf(String p1) {
        return (MemoryPolicy)valueOf(MemoryPolicy.class, p1);
    }
    
    public static MemoryPolicy[] values() {
        return (MemoryPolicy[])$VALUES.clone();
    }
    public static final enum MemoryPolicy NO_CACHE = new MemoryPolicy("NO_CACHE", 0x0, 0x1);
    public static final enum MemoryPolicy NO_STORE = new MemoryPolicy("NO_STORE", 0x1, 0x2);
    
    static boolean shouldReadFromMemoryCache(int p1) {
        return (NO_CACHE.index == 0);
    }
    
    static boolean shouldWriteToMemoryCache(int p1) {
        return (NO_STORE.index == 0);
    }
    
    private MemoryPolicy(String p1, int p2, int p3) {
        super(p1, p2);
        index = p3;
    }
}
