/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;


public final enum class NetworkPolicy extends Enum {
    final int index;
    
    public static NetworkPolicy valueOf(String p1) {
        return (NetworkPolicy)valueOf(NetworkPolicy.class, p1);
    }
    
    public static NetworkPolicy[] values() {
        return (NetworkPolicy[])$VALUES.clone();
    }
    public static final enum NetworkPolicy NO_CACHE = new NetworkPolicy("NO_CACHE", 0x0, 0x1);
    public static final enum NetworkPolicy NO_STORE = new NetworkPolicy("NO_STORE", 0x1, 0x2);
    public static final enum NetworkPolicy OFFLINE = new NetworkPolicy("OFFLINE", 0x2, 0x4);
    
    public static boolean shouldReadFromDiskCache(int p1) {
        return (NO_CACHE.index == 0);
    }
    
    public static boolean shouldWriteToDiskCache(int p1) {
        return (NO_STORE.index == 0);
    }
    
    public static boolean isOfflineOnly(int p1) {
        return (OFFLINE.index != 0);
    }
    
    private NetworkPolicy(String p1, int p2, int p3) {
        super(p1, p2);
        index = p3;
    }
}
