/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;
import android.graphics.drawable.Drawable;

final class TargetAction extends Action {
    
    TargetAction(Picasso p1, Target p2, Request p3, int p4, int p5, Drawable p6, String p7, Object p8, int p9) {
        super(p1, p2, p3, p4, p5, p9, p6, p7, p8, false);
    }
    
    void complete(Bitmap p1, Picasso.LoadedFrom p2) {
        // :( Parsing error. Please contact me.
    }
    
    void error() {
        // :( Parsing error. Please contact me.
    }
}
