/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.drawable.Drawable;
import android.graphics.Bitmap;

public interface abstract class Target {
    
    public abstract void onBitmapFailed(Drawable p1);
    
    
    public abstract void onBitmapLoaded(Bitmap p1, Picasso.LoadedFrom p2);
    
    
    public abstract void onPrepareLoad(Drawable p1);
    
}
