/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.squareup.picasso;

import android.graphics.Bitmap;

public interface abstract class Transformation {
    
    public abstract String key();
    
    
    public abstract Bitmap transform(Bitmap p1);
    
}
